name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: mtrudel/elixir-ci-actions/.github/workflows/test.yml@main
  lint:
    uses: mtrudel/elixir-ci-actions/.github/workflows/lint.yml@main
  h2spec:
    uses: ./.github/workflows/h2spec.yml
  autobahn:
    uses: ./.github/workflows/autobahn.yml
  re-run:
    permissions:
      actions: write
    needs: [test, lint, h2spec, autobahn]
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run rerun.yml -F run_id=${{ github.run_id }}
